name: wakaluxe
description: move with comfort and style.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  auto_route: ^6.3.0
  bloc: ^8.1.1
  collection: ^1.17.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_core: ^2.11.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  flutter_hicons: ^0.0.1
  flutter_image_stack: ^0.0.6
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.18
  flutter_screenutil: ^5.7.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.5
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.2.6
  hydrated_bloc: ^8.0.0
  intl: ^0.17.0
  introduction_screen: ^3.1.8
  mask_text_input_formatter: ^2.4.0
  material_color_utilities: ^0.2.0
  palette_generator: ^0.3.3+2
  path_provider: ^2.0.13
  pinput: ^2.2.31
  url_launcher: ^6.1.10

dev_dependencies:
  auto_route_generator: ^6.2.0
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  fast_i18n: ^5.12.6
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/intro/
    - assets/images/
    - assets/icons/
    - assets/icons/auth/
    - assets/illustrations/
    - assets/icons/hicon/linear/
    - assets/icons/hicon/bold/


  fonts:
    - family: WakaluxIcons
      fonts:
        - asset: fonts/WakaluxIcons.ttf

flutter_native_splash:
  background_image: "assets/intro/splash.png"
