// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG9TV4wsjMaq4-wbNeSwX9iM7UBpLYSsg',
    appId: '1:144237079404:web:8f676962206f2c532c6149',
    messagingSenderId: '144237079404',
    projectId: 'wakaluxe-app',
    authDomain: 'wakaluxe-app.firebaseapp.com',
    storageBucket: 'wakaluxe-app.appspot.com',
    measurementId: 'G-PJP4LKMC1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQjzaoLJCI_0JuwEqYlUUQC5h-mdNivcQ',
    appId: '1:144237079404:android:805337e24da5dde32c6149',
    messagingSenderId: '144237079404',
    projectId: 'wakaluxe-app',
    storageBucket: 'wakaluxe-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVB-9cpDCk5zvhnYz0NdYxPSvF7RKIrek',
    appId: '1:144237079404:ios:5788aae9fe34d2a82c6149',
    messagingSenderId: '144237079404',
    projectId: 'wakaluxe-app',
    storageBucket: 'wakaluxe-app.appspot.com',
    iosClientId: '144237079404-912216rapb1rcormk0b064cbocjehid9.apps.googleusercontent.com',
    iosBundleId: 'com.apps.ictu.wakaluxe',
  );
}
