// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiOsA3QNDI67lIkAECTZh8iRkX0LoM3cw',
    appId: '1:297590824503:web:6ab9dd24dbb6bcac96e9b2',
    messagingSenderId: '297590824503',
    projectId: 'wakaluxe-mobile',
    authDomain: 'wakaluxe-mobile.firebaseapp.com',
    storageBucket: 'wakaluxe-mobile.appspot.com',
    measurementId: 'G-11HRCQ2V2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvTvxZ3zrZRICj3fJhYe0L_T6Uonan_U0',
    appId: '1:297590824503:android:d216610245324ffa96e9b2',
    messagingSenderId: '297590824503',
    projectId: 'wakaluxe-mobile',
    storageBucket: 'wakaluxe-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb0u6rY4Cu3b9hCRNd7SywU8bumsy0udU',
    appId: '1:297590824503:ios:e8ba6e252587f7dc96e9b2',
    messagingSenderId: '297590824503',
    projectId: 'wakaluxe-mobile',
    storageBucket: 'wakaluxe-mobile.appspot.com',
    androidClientId:
        '297590824503-2f0paft677kibqvso1p0q80u0ncui5li.apps.googleusercontent.com',
    iosClientId:
        '297590824503-4fe7slhfu2ihaj4prhh07k8qi7nq5ugb.apps.googleusercontent.com',
    iosBundleId: 'com.apps.ictu.wakaluxe',
  );
}
